---
- name: Netbox API call
  hosts: localhost
  connection: local
  gather_facts: no
  
  # Not needed here because it's imported using requirements file
  # collections:
  #   - netbox.netbox

  # Needs to ingest/replace vars from/with values from vault
  # vars:
  #   - app_url: ""
  #   - app_token: ""

  tasks:
    - netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ app_url }}"
        netbox_token: "{{ app_token }}"
        data:
          name: "myappsrv01"
          vcpus: "2"
          memory: "8"
          disk: "75"
        state: present
        validate_certs: no

    - name: print a message
      ansible.builtin.debug:
        msg: "Hello World!"